"""add_onboarding_models

Revision ID: 0cf7c4cce8d2
Revises: c7bc5eb5cc4d
Create Date: 2026-05-23 12:13:20.805359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf7c4cce8d2'
down_revision: Union[str, None] = 'c7bc5eb5cc4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrolled_students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('enrollment_number', sa.String(length=30), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('credentials_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrolled_students_email'), 'enrolled_students', ['email'], unique=True)
    op.create_index(op.f('ix_enrolled_students_enrollment_number'), 'enrolled_students', ['enrollment_number'], unique=True)
    op.create_index(op.f('ix_enrolled_students_id'), 'enrolled_students', ['id'], unique=False)
    op.create_table('student_access_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('enrollment_number', sa.String(length=30), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='access_request_status_enum'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_access_requests_email'), 'student_access_requests', ['email'], unique=False)
    op.create_index(op.f('ix_student_access_requests_enrollment_number'), 'student_access_requests', ['enrollment_number'], unique=False)
    op.create_index(op.f('ix_student_access_requests_id'), 'student_access_requests', ['id'], unique=False)
    # Add must_change_password as nullable first, populate with default, then alter to NOT NULL
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET must_change_password = False")
    op.alter_column('users', 'must_change_password', nullable=False)
    
    op.add_column('users', sa.Column('branch', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'branch')
    op.drop_column('users', 'must_change_password')
    op.drop_index(op.f('ix_student_access_requests_id'), table_name='student_access_requests')
    op.drop_index(op.f('ix_student_access_requests_enrollment_number'), table_name='student_access_requests')
    op.drop_index(op.f('ix_student_access_requests_email'), table_name='student_access_requests')
    op.drop_table('student_access_requests')
    op.drop_index(op.f('ix_enrolled_students_id'), table_name='enrolled_students')
    op.drop_index(op.f('ix_enrolled_students_enrollment_number'), table_name='enrolled_students')
    op.drop_index(op.f('ix_enrolled_students_email'), table_name='enrolled_students')
    op.drop_table('enrolled_students')
    # ### end Alembic commands ###
