"""add_doubt_upvotes

Revision ID: 29d18a62c1b8
Revises: 04ca4ebff29c
Create Date: 2026-05-20 15:29:46.087530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d18a62c1b8'
down_revision: Union[str, None] = '04ca4ebff29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doubt_upvotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['doubt_answers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'answer_id', name='uq_student_answer_upvote')
    )
    op.create_index(op.f('ix_doubt_upvotes_id'), 'doubt_upvotes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doubt_upvotes_id'), table_name='doubt_upvotes')
    op.drop_table('doubt_upvotes')
    # ### end Alembic commands ###
