"""add_subject_archive_fields

Revision ID: 540543bfcb79
Revises: 0cf7c4cce8d2
Create Date: 2026-06-04 15:56:55.886134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540543bfcb79'
down_revision: Union[str, None] = '0cf7c4cce8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('subjects', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'archived_at')
    op.drop_column('subjects', 'is_archived')
    # ### end Alembic commands ###
