"""add_doubt_question_upvote

Revision ID: 80d1082c5333
Revises: b4f75f032e5b
Create Date: 2026-05-20 16:10:10.120657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d1082c5333'
down_revision: Union[str, None] = 'b4f75f032e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doubt_question_upvotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('doubt_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['doubt_id'], ['doubts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'doubt_id', name='uq_user_doubt_upvote')
    )
    op.create_index(op.f('ix_doubt_question_upvotes_id'), 'doubt_question_upvotes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doubt_question_upvotes_id'), table_name='doubt_question_upvotes')
    op.drop_table('doubt_question_upvotes')
    # ### end Alembic commands ###
