"""add_is_verified_by_admin

Revision ID: b4f75f032e5b
Revises: 29d18a62c1b8
Create Date: 2026-05-20 15:42:20.186925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f75f032e5b'
down_revision: Union[str, None] = '29d18a62c1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doubt_answers', sa.Column('is_verified_by_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doubt_answers', 'is_verified_by_admin')
    # ### end Alembic commands ###
