"""add_course_semester_system

Revision ID: c7bc5eb5cc4d
Revises: 80d1082c5333
Create Date: 2026-05-23 10:34:23.088452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7bc5eb5cc4d'
down_revision: Union[str, None] = '80d1082c5333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('total_semesters', sa.Integer(), nullable=False),
    sa.Column('duration_years', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('events', sa.Column('course_id', sa.UUID(), nullable=True))
    op.add_column('events', sa.Column('semester_number', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'courses', ['course_id'], ['id'])
    op.add_column('notes', sa.Column('course_id', sa.UUID(), nullable=True))
    op.add_column('notes', sa.Column('semester_number', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'courses', ['course_id'], ['id'])
    op.add_column('subjects', sa.Column('course_id', sa.UUID(), nullable=True))
    op.add_column('subjects', sa.Column('semester_number', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subjects', 'courses', ['course_id'], ['id'])
    op.add_column('timetable', sa.Column('course_id', sa.UUID(), nullable=True))
    op.add_column('timetable', sa.Column('semester_number', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'timetable', 'courses', ['course_id'], ['id'])
    op.add_column('users', sa.Column('course_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('current_semester', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('enrollment_no', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('roll_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('section', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('cgpa', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('profile_photo_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('admission_year', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['enrollment_no'])
    op.create_foreign_key(None, 'users', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'admission_year')
    op.drop_column('users', 'profile_photo_url')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'cgpa')
    op.drop_column('users', 'section')
    op.drop_column('users', 'roll_number')
    op.drop_column('users', 'enrollment_no')
    op.drop_column('users', 'current_semester')
    op.drop_column('users', 'course_id')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_column('timetable', 'semester_number')
    op.drop_column('timetable', 'course_id')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'semester_number')
    op.drop_column('subjects', 'course_id')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'semester_number')
    op.drop_column('notes', 'course_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'semester_number')
    op.drop_column('events', 'course_id')
    op.drop_table('courses')
    # ### end Alembic commands ###
